---
# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing

on:
  push:
    branches: ["main", "develop"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, "3.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --no-ansi
      - name: Test with pytest
        run: |
          poetry run pytest

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build distribution
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade poetry
          /home/runner/.local/bin/poetry build
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@e777b333
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
