---
name: Code Style


# yamllint disable-line rule:truthy
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  check-style:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Lint with black
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run black --check x690
      - name: Check import ordering
        run: |
          set -o pipefail
          poetry run isort --check-only --diff --recursive x690 | pygmentize
      - name: Check Types
        run: |
          poetry run mypy --strict -p x690
      - name: Check for unused code
        run: |
          set -o pipefail
          poetry run vulture vulture-whitelist.py x690 | pygmentize
      - name: Check for obsolete vulture-whitelist items
        run: |
          poetry run vulture-whitelist.py
