name: Build & Publish Docs

on:
  push:
    branches: [ "main", "docs" ]
  pull_request:
    branches: [ "main", "docs" ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "docs/"
        pre-build-command: "pip install . && sphinx-apidoc -o docs/api x690"
    - name: Commit documentation changes
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        git clone https://github.com/exhuma/x690.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Build distribution
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      run: |
        pip install wheel
        python setup.py sdist
        python setup.py bdist_wheel
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@e777b333
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
